import type { Context } from "hono";

/**
 * Augment this interface in your project's src/context.ts to wire in
 * your CloudflareBindings (generated by `pnpm cf-typegen`).
 *
 *   declare module "@wilt/core" {
 *     interface WiltBindings extends CloudflareBindings {}
 *   }
 *
 * After that, every `AppContext` parameter automatically carries your binding
 * types — no need to pass the generic manually.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface WiltBindings {}

export type AppContext<B extends object = WiltBindings> = Context<{
  Bindings: B;
}>;
